BEGIN;

-- ============================================================
-- 1) TABLE: profiles
-- ============================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY,                 -- must match auth.users.id (set by your app / service)
  email text,
  full_name text,
  avatar_url text,
  updated_at timestamptz DEFAULT now()
);

-- Case-insensitive index for email lookups
CREATE INDEX IF NOT EXISTS idx_profiles_email_lower
  ON public.profiles (lower(email));

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policy: allow users to SELECT their own profile
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policy
    WHERE polname = 'profiles_select_own'
      AND polrelid = 'public.profiles'::regclass
  ) THEN
    CREATE POLICY profiles_select_own ON public.profiles
      FOR SELECT
      USING (auth.uid() = id);
  END IF;
END$$;

-- Policy: allow users to INSERT their own profile (auth.uid() must equal id)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policy
    WHERE polname = 'profiles_insert_own'
      AND polrelid = 'public.profiles'::regclass
  ) THEN
    CREATE POLICY profiles_insert_own ON public.profiles
      FOR INSERT
      WITH CHECK (auth.uid() = id);
  END IF;
END$$;

-- Policy: allow users to UPDATE their own profile
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policy
    WHERE polname = 'profiles_update_own'
      AND polrelid = 'public.profiles'::regclass
  ) THEN
    CREATE POLICY profiles_update_own ON public.profiles
      FOR UPDATE
      USING (auth.uid() = id)
      WITH CHECK (auth.uid() = id);
  END IF;
END$$;


-- ============================================================
-- 2) TABLE: user_anime_list
-- ============================================================
CREATE TABLE IF NOT EXISTS public.user_anime_list (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) NOT NULL,
  mal_id integer NOT NULL,
  status text,
  title text,
  image_url text,
  total_episodes integer,
  progress integer DEFAULT 0,
  score integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- Unique constraint: one (user, mal_id) pair
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_anime_list_user_mal_unique
  ON public.user_anime_list (user_id, mal_id);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_anime_list_user_created_at
  ON public.user_anime_list (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_anime_list_user_mal
  ON public.user_anime_list (user_id, mal_id);

-- Normalize existing nulls (only set if column exists and values are NULL)
-- (If DB already had rows without progress/score, this will update them)
UPDATE public.user_anime_list
  SET progress = 0
  WHERE progress IS NULL;

UPDATE public.user_anime_list
  SET score = 0
  WHERE score IS NULL;

-- Enable RLS
ALTER TABLE public.user_anime_list ENABLE ROW LEVEL SECURITY;

-- Policy: allow users to SELECT only their rows
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policy
    WHERE polname = 'user_anime_select_own'
      AND polrelid = 'public.user_anime_list'::regclass
  ) THEN
    CREATE POLICY user_anime_select_own ON public.user_anime_list
      FOR SELECT
      USING (auth.uid() = user_id);
  END IF;
END$$;

-- Policy: allow users to INSERT rows for themselves
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policy
    WHERE polname = 'user_anime_insert_own'
      AND polrelid = 'public.user_anime_list'::regclass
  ) THEN
    CREATE POLICY user_anime_insert_own ON public.user_anime_list
      FOR INSERT
      WITH CHECK (auth.uid() = user_id);
  END IF;
END$$;

-- Policy: allow users to UPDATE their rows
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policy
    WHERE polname = 'user_anime_update_own'
      AND polrelid = 'public.user_anime_list'::regclass
  ) THEN
    CREATE POLICY user_anime_update_own ON public.user_anime_list
      FOR UPDATE
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END$$;

-- Policy: allow users to DELETE their rows
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policy
    WHERE polname = 'user_anime_delete_own'
      AND polrelid = 'public.user_anime_list'::regclass
  ) THEN
    CREATE POLICY user_anime_delete_own ON public.user_anime_list
      FOR DELETE
      USING (auth.uid() = user_id);
  END IF;
END$$;

COMMIT;
